#!/usr/bin/env node
/**
 * design/tokens.json  ->  src/app/tokens.generated.css
 *
 * Emits a Tailwind v4 `@theme` block plus light and dark theme overrides, and
 * FAILS THE BUILD if any text pairing drops below WCAG AA in EITHER theme.
 *
 * The contrast gate is the point of this script. Without it, "both themes pass
 * AA" is a claim in a document rather than a property of the system.
 *
 * Usage:
 *   node scripts/build-tokens.mjs               generate + check
 *   node scripts/build-tokens.mjs --check-only  check only, write nothing
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC = resolve(root, 'design/tokens.json')
const OUT = resolve(root, 'src/app/tokens.generated.css')
const checkOnly = process.argv.includes('--check-only')

const AA_NORMAL = 4.5

const tokens = JSON.parse(readFileSync(SRC, 'utf8'))

/* ---------------------------------------------------------------- helpers */

/** Resolve `{primitive.color.x.y}` refs and unwrap documented `{value,...}` leaves. */
function deref(value) {
  if (value && typeof value === 'object' && 'value' in value) return deref(value.value)
  if (typeof value !== 'string') return value
  const m = /^\{([^}]+)\}$/.exec(value.trim())
  if (!m) return value
  const hit = m[1].split('.').reduce((acc, k) => (acc == null ? acc : acc[k]), tokens)
  if (hit === undefined) throw new Error(`Unresolved token reference: ${value}`)
  return deref(hit)
}

function relativeLuminance(hex) {
  const h = hex.replace('#', '')
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255)
  const lin = (c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4)
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)
}

function contrastRatio(a, b) {
  const [hi, lo] = [relativeLuminance(a), relativeLuminance(b)].sort((x, y) => y - x)
  return (hi + 0.05) / (lo + 0.05)
}

const kebab = (s) =>
  s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').replace(/\./g, '_').toLowerCase()

/** Documentation keys that live beside values but must never become CSS props. */
const META = new Set(['contrast', 'means', 'note', 'use', 'on', 'exempt'])

function flatten(node, prefix, out = []) {
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$') || META.has(key)) continue
    const name = `${prefix}-${kebab(key)}`
    if (value && typeof value === 'object') {
      if ('value' in value) out.push([name, deref(value.value)])
      else flatten(value, name, out)
    } else {
      out.push([name, deref(value)])
    }
  }
  return out
}

/* ------------------------------------------------------------ the AA gate */

const failures = []
let checked = 0
let worst = { label: '—', ratio: Infinity }

function checkTheme(themeName) {
  const theme = tokens.semantic[themeName]

  const record = (label, fg, bg, exempt) => {
    const f = deref(fg)
    const b = deref(bg)
    if (typeof f !== 'string' || !f.startsWith('#')) return
    if (typeof b !== 'string' || !b.startsWith('#')) return
    const ratio = contrastRatio(f, b)
    if (exempt) return
    checked++
    if (ratio < worst.ratio) worst = { label: `${themeName}/${label}`, ratio }
    if (ratio < AA_NORMAL) {
      failures.push(`${themeName} · ${label}: ${ratio.toFixed(2)}:1 (needs ${AA_NORMAL}:1)`)
    }
  }

  for (const [key, entry] of Object.entries(theme.text)) {
    if (key.startsWith('$')) continue
    const surfaceKey = entry.on?.split('.')[1]
    const bg = surfaceKey ? theme.surface[surfaceKey] : undefined
    if (!bg) continue
    record(`text.${key} on ${entry.on}`, entry.value, bg, entry.exempt)
  }

  for (const [key, entry] of Object.entries(theme.status)) {
    if (key.startsWith('$')) continue
    record(`status.${key}`, entry.fg, entry.bg, false)
  }
}

checkTheme('light')
checkTheme('dark')

/* ------------------------------------------------------------ CSS output */

/** Emit a theme's semantic colours as `--color-*` overrides. */
function themeVars(themeName, indent = '  ') {
  const theme = tokens.semantic[themeName]
  return [
    ...flatten(theme.surface, '--color-surface'),
    ...flatten(theme.text, '--color-text'),
    ...flatten(theme.border, '--color-border'),
    ...flatten(theme.status, '--color-status'),
  ]
    .map(([n, v]) => `${indent}${n}: ${v};`)
    .join('\n')
}

function buildCss() {
  const p = tokens.primitive
  const lines = []

  lines.push('/* GENERATED by scripts/build-tokens.mjs — DO NOT EDIT. */')
  lines.push('/* Source of truth: design/tokens.json */')
  lines.push('')

  lines.push('@theme {')
  const push = (pairs, comment) => {
    lines.push(`  /* ${comment} */`)
    for (const [name, value] of pairs) lines.push(`  ${name}: ${value};`)
    lines.push('')
  }

  push(flatten(p.color, '--color'), 'primitive colour ramps')
  // Light is the @theme default so Tailwind generates the utility classes.
  lines.push('  /* semantic colours — light theme is the default */')
  lines.push(themeVars('light'))
  lines.push('')
  push(flatten(p.space, '--spacing'), 'spacing scale')
  push(flatten(p.radius, '--radius'), 'radii')
  push(flatten(p.shadow, '--shadow'), 'elevation')
  push(flatten(p.duration, '--duration'), 'motion durations')
  push(flatten(p.easing, '--ease'), 'motion easing')
  push(flatten(p.fontFamily, '--font'), 'font families')
  push(flatten(p.fontWeight, '--font-weight'), 'font weights')
  push(flatten(p.fontSize, '--text'), 'latin type scale')
  push(flatten(p.fontSizeArabic, '--text-ar'), 'arabic type scale (~8-12% larger)')
  push(flatten(p.lineHeight, '--leading'), 'line heights')
  push(flatten(p.tracking, '--tracking'), 'letter spacing (LATIN ONLY — never Arabic)')
  push(flatten(p.breakpoint, '--breakpoint'), 'breakpoints')
  push(flatten(p.container, '--container'), 'containers')
  push(flatten(p.zIndex, '--z'), 'z-index scale')
  push(flatten(tokens.component, '--component'), 'component-specific')
  lines.push('}')
  lines.push('')

  /* -- dark theme ------------------------------------------------------- */
  lines.push('/* Dark theme. Authored alongside light — an inversion would break brand and contrast. */')
  lines.push('@media (prefers-color-scheme: dark) {')
  lines.push('  :root:not([data-theme="light"]) {')
  lines.push(themeVars('dark', '    '))
  lines.push('    color-scheme: dark;')
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push(':root[data-theme="dark"] {')
  lines.push(themeVars('dark', '  '))
  lines.push('  color-scheme: dark;')
  lines.push('}')
  lines.push('')
  lines.push(':root[data-theme="light"] {')
  lines.push(themeVars('light', '  '))
  lines.push('  color-scheme: light;')
  lines.push('}')
  lines.push('')

  /* -- locale-aware type ------------------------------------------------ */
  lines.push('/* Arabic remaps the shared type scale — components never branch on locale. */')
  lines.push(':root {')
  for (const k of Object.keys(p.fontSize)) {
    lines.push(`  --type-${kebab(k)}: var(--text-${kebab(k)});`)
  }
  lines.push('  --leading-body: var(--leading-normal);')
  lines.push('  --leading-heading: var(--leading-tight);')
  lines.push('  --font-ui: var(--font-latin);')
  lines.push('  --tracking-display: var(--tracking-tight);')
  lines.push('}')
  lines.push('')
  lines.push('html[lang="ar"] {')
  for (const k of Object.keys(p.fontSizeArabic)) {
    lines.push(`  --type-${kebab(k)}: var(--text-ar-${kebab(k)});`)
  }
  lines.push('  --leading-body: var(--leading-arabic-normal);')
  lines.push('  --leading-heading: var(--leading-arabic-tight);')
  lines.push('  --font-ui: var(--font-arabic);')
  // Arabic is never letter-spaced — it severs the connecting strokes.
  lines.push('  --tracking-display: var(--tracking-normal);')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

/* -------------------------------------------------------------- reporting */

if (failures.length) {
  console.error('\n✗ Contrast gate FAILED — below WCAG AA:\n')
  for (const f of failures) console.error(`   ${f}`)
  console.error('\nFix design/tokens.json. Do not lower the threshold.\n')
  process.exit(1)
}

console.log(
  `✓ Contrast: ${checked} pairings across light + dark, all above ${AA_NORMAL}:1 ` +
    `(tightest: ${worst.label} at ${worst.ratio.toFixed(2)}:1)`,
)

if (checkOnly) process.exit(0)

const css = buildCss()
mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, css, 'utf8')
console.log(`✓ Tokens: wrote ${css.split('\n').length} lines to src/app/tokens.generated.css`)
